### ISSUE TITLE
خطا در اجرای template مربوط به iust

### ISSUE THREAD

**Issue by maryammohabbati** [m-zakeri/ZMOST#1]
با عرض سلام و ادب و احترام و تشکر بابت تهیه و تنظیم تمپلیت مربوطه
دوستان در اجرای تمپلیت قرار داده شده مشکلی ندارند اما بنده با نصب livetex 2021  و texstudio 3.0.4 هنگام اجرای فایل main  با چندین خطا مشابه 
Missing \begin{document}.
Extra \fi.
,...
مواجه می شوم، لطفا راهنمایی نمایید.
با تشکر و تجدید احترام

**Comment by m-zakeri** [comment]
Hey,
I found some bugs in math-typing-related packages. 
Specifically, the command `\setdigitfont` is no longer supported by TeX Live 2021 and upper.
It should be replaced with `\setmathdigitfont` in the `settings.tex` file.
Now, all things work fine in release 0.2.0.

**Comment by maryammohabbati** [comment]
با عرض سلام مجدد
هنگام استفاده از autoref برای الگوریتم ها در متن کامپایل شده کلمه ی الگوریتم به صورت انگلیسی نمایش داده می شود.
