### ISSUE TITLE
Several issues with the template

### ISSUE THREAD

**Issue by SajjadSM** [m-zakeri/ZMOST#2]
باسلام
من چندتا مشکل با تمپلیت داشتم، ممنون میشم اگر راهنمایی کنید.
فایل های تمپلیت رو از همین ریپو دریافت کردم و بدون هیچ تغییری با دستور `xelatex.exe -synctex=1 -interaction=nonstopmode "maintext.tex"` کامپایل رو انجام دادم ولی فایل pdf خروجی مشکلات زیادی از جمله چینش چپ به راست کلمات، انگلیسی شدن برخی از و عنوان‌ها را دارد. فایل خروجی هم پیوست شده. باتشکر
textlive 2024 هم نصب شده روی سیستم.
[maintext.pdf](https://github.com/user-attachments/files/16056110/maintext.pdf)

![image](https://github.com/m-zakeri/ZMOST/assets/38383587/d07e1c8e-094a-4fda-80e3-5da30cf27521)

**Comment by SajjadSM** [comment]
به نظر میرسه پکیج lettrine باعث این مشکل شده و با کامنت کردنش همه اشکالات گفته شده حل میشه (حداقل با ورژن جدید XeTeX این مشکل وجود داره)
کار این پکیج چی هست و نبودش چه مشکلی ممکنه ایجاد کنه؟

 `This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)`

**Comment by m-zakeri** [comment]
Please recheck the new update. All issues with TeX Live 2024 have been fixed.
